// Generado desde manifest_lovable_images.json — fotos reales de Cinco Lagos
export type Photo = { url: string; alt: string; w: number; h: number };

export const photos = {
  p01: { url: "/images/general/cinco-lagos-vista-01.png", alt: "Vista al lago desde la terraza, con dos sillas de madera frente al agua turquesa.", w: 1285, h: 1300 },
  p02: { url: "/images/cabanas-pequenas/cabana-pequena-01.png", alt: "Exterior de cabañas pequeñas tipo A-frame con fachadas de colores.", w: 1285, h: 735 },
  p03: { url: "/images/cabanas-pequenas/cabana-pequena-02.png", alt: "Interior con dos camas matrimoniales en cabaña pequeña.", w: 365, h: 180 },
  p04: { url: "/images/cabanas-pequenas/cabana-pequena-03.png", alt: "Interior de madera con cama, puerta y ventanas.", w: 365, h: 180 },
  p05: { url: "/images/cabanas-pequenas/cabana-pequena-04.png", alt: "Interior con puerta abierta y vista al lago desde balcón.", w: 365, h: 180 },
  p06: { url: "/images/cabanas-pequenas/cabana-pequena-05.png", alt: "Habitación con pared roja, cama y acceso a baño privado.", w: 365, h: 180 },
  p07: { url: "/images/cabanas-pequenas/cabana-pequena-06.png", alt: "Cama individual en interior de cabaña pequeña.", w: 365, h: 180 },
  p08: { url: "/images/cabanas-pequenas/cabana-pequena-07.png", alt: "Detalle de sofá o banca interior junto a cama.", w: 365, h: 180 },
  p09: { url: "/images/cabana-cristal/cabana-cristal-01.png", alt: "Interior de cabaña de cristal con ventanales y vista al lago. Usar como hero de la sección.", w: 1285, h: 735 },
  p10: { url: "/images/cabana-cristal/cabana-cristal-02.png", alt: "Exterior de cabaña de cristal con terraza y vista al lago.", w: 365, h: 273 },
  p11: { url: "/images/cabana-cristal/cabana-cristal-03.png", alt: "Cama junto a ventanales con vista al lago.", w: 365, h: 273 },
  p12: { url: "/images/cabana-cristal/cabana-cristal-04.png", alt: "Interior de madera en vista tipo 360 con mobiliario.", w: 365, h: 273 },
  p13: { url: "/images/cabana-grande/cabana-grande-01.png", alt: "Interior amplio de madera con puerta abierta. Usar como hero de la sección.", w: 1285, h: 735 },
  p14: { url: "/images/cabana-grande/cabana-grande-02.png", alt: "Exterior de cabaña grande con terraza y techo.", w: 365, h: 180 },
  p15: { url: "/images/cabana-grande/cabana-grande-03.png", alt: "Habitación matrimonial con interior de madera.", w: 365, h: 180 },
  p16: { url: "/images/cabana-grande/cabana-grande-04.png", alt: "Habitación en planta baja con cama matrimonial.", w: 365, h: 180 },
  p17: { url: "/images/cabana-grande/cabana-grande-05.png", alt: "Planta alta con dos camas matrimoniales.", w: 365, h: 180 },
  p18: { url: "/images/cabana-grande/cabana-grande-06.png", alt: "Baño privado con azulejo gris y negro.", w: 365, h: 180 },
  p19: { url: "/images/cabana-mayor/cabana-mayor-01.png", alt: "Habitación matrimonial de madera. Usar como hero de la sección.", w: 1285, h: 735 },
  p20: { url: "/images/cabana-mayor/cabana-mayor-02.png", alt: "Habitación de madera con dos camas.", w: 365, h: 180 },
  p21: { url: "/images/cabana-mayor/cabana-mayor-03.png", alt: "Baño privado con azulejo rojo y negro.", w: 365, h: 180 },
  p22: { url: "/images/cabana-mayor/cabana-mayor-04.png", alt: "Terraza con silla y vista directa al lago.", w: 365, h: 180 },
  p23: { url: "/images/cabana-mayor/cabana-mayor-05.png", alt: "Sala o terraza cubierta con vista al lago.", w: 365, h: 180 },
  p24: { url: "/images/cabana-mayor/cabana-mayor-06.png", alt: "Interior verde con escalera hacia planta alta.", w: 365, h: 180 },
  p25: { url: "/images/galeria/galeria-01.png", alt: "Imagen de resumen con cama y acceso a baño.", w: 642, h: 299 },
  p26: { url: "/images/galeria/galeria-02.png", alt: "Imagen de resumen de baño privado rojo y negro.", w: 642, h: 299 },
  p27: { url: "/images/galeria/galeria-03.png", alt: "Imagen de resumen del exterior de la cabaña de cristal frente al lago.", w: 642, h: 299 },
  p28: { url: "/images/galeria/galeria-04.png", alt: "Imagen de resumen de baño privado gris y negro.", w: 642, h: 299 },
  p29: { url: "/images/general/qr-disponibilidad.png", alt: "QR de consulta de disponibilidad visible en la página final del PDF. En web puede reemplazarse por botón de WhatsApp o disponibilidad.", w: 207, h: 205 },
} satisfies Record<string, Photo>;
